name: form_builder_image_picker
description: Images picker field for FlutterFormBuilder. Get images from gallery or camera
version: 3.0.0
repository: https://github.com/flutter-form-builder-ecosystem/form_builder_image_picker
issue_tracker: https://github.com/flutter-form-builder-ecosystem/form_builder_image_picker/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.3.1
  async: ^2.9.0
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_lints: ^2.0.1
