name: form_builder_image_picker
description: Field for picking image(s) from Gallery or Camera for flutter_form_builder package
version: 2.0.0
homepage: https://github.com/danvick/form_builder_image_picker

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: 7.1.1
  image_picker: 0.8.4+4

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
