name: Base

on:
  push:
    branches: [main]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check broken links
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "**/*.md"

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      - name: Format code
        run: flutter format --dry-run --set-exit-if-changed .
      - name: Analyze static code
        run: flutter analyze
      # - name: Run tests
      #   run: flutter test
      - name: Check publish warnings
        run: dart pub publish --dry-run
      - name: Build example
        run: |
          cd example
          flutter build appbundle --debug
          flutter build ios --debug --no-codesign
          flutter build web

      # - name: Upload coverage to Codecov
      #   if: ${{ matrix.channel == 'stable' }}
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: coverage/lcov.info
      #     flags: unittests
      #     name: form_builder_image_picker

  deployment:
    if: ${{ github.ref_type == 'tag' }}
    needs: build
    name: Deploy package
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Publish package
        run: dart pub publish -v -f
      - name: Build changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}

